repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-case-conflict
    -   id: debug-statements
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
    -   id: detect-private-key
    -   id: fix-encoding-pragma
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-merge-conflict
-   repo: https://github.com/asottile/blacken-docs
    rev: v0.4.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.3b0]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.0
    hooks:
    -   id: python-use-type-annotations
    -i  id: rst-backtics
