# Config file for automatic testing at travis-ci.org
language: python
env:
  global:
    - FLASK_APP=autoapp.py 
    - FLASK_DEBUG=1 
    - DATABASE_URL="sqlite:////tmp/dev.db"
    - SECRET_KEY="not-so-secret"
matrix:
  include: 
    - python: 3.6
      dist: trusty
    - python: 3.7 
      dist: xenial
install:
  - pip install pipenv
  - pipenv install --dev
  - nvm install 6.10
  - nvm use 6.10
  - npm install
before_script:
  - npm run lint
  - npm run build
  - flask lint
script: 
  - pytest --cov=servicedesk
after_script:
  - codecov