# Config file for automatic testing at travis-ci.org
language: python
env:
  global:
    - FLASK_APP=autoapp.py 
    - FLASK_DEBUG=1 
    - DATABASE_URL="sqlite:////tmp/dev.db"
    - SECRET_KEY="not-so-secret"
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pipenv install --dev
  - nvm install 6.10
  - nvm use 6.10
  - npm install
before_script:
  - npm run lint
  - npm run build
  - flask lint
script: flask test
